# Generated by Django 4.1.3 on 2022-12-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='distance',
            options={'verbose_name': 'distance', 'verbose_name_plural': 'distances'},
        ),
    ]
