# Generated by Django 4.1.3 on 2022-12-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_options_alter_distance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='city.city'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='city.city'),
        ),
    ]
