# Generated by Django 4.1.3 on 2022-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='name')),
                ('rating', models.FloatField(default=0.0, verbose_name='rating')),
                ('salary', models.FloatField(default=0.0, verbose_name='salary')),
            ],
        ),
    ]
