# Generated by Django 4.1.3 on 2022-12-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=24, verbose_name='model')),
                ('engine', models.IntegerField(verbose_name='amount of horsepower')),
                ('tank', models.IntegerField(verbose_name='tank size')),
                ('mileage', models.IntegerField(default=0, verbose_name='mileage')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
        ),
    ]
