# Generated by Django 4.1.3 on 2022-12-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40, verbose_name='model')),
            ],
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='truck.truckmodel'),
        ),
    ]
